SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += ../rtl/risc_pkg.sv ../rtl/immediate_gen.sv

TOPLEVEL = immediate_gen
MODULE = test_immediate_gen

include $(shell cocotb-config --makefiles)/Makefile.sim
